### PR TITLE
Initial beer api with button

### PR DESCRIPTION
**Pull request by APOLAKl**
Added button to HTML with CSS codes(feel free to change the button supplied), upon click event, added beer API data for 1 random beer with name, tagline, volume, description, and 3 food pairings.

### CODE REVIEW

**Review by MSchuur — DISMISSED** [review]
From what I am seeing everything lood good.

**Comment by MSchuur** [comment]
Chad Where did all the CSS come from. You have over 300 lines?

**Comment by APOLAKl** [comment]
> Chad Where did all the CSS come from. You have over 300 lines?

Yes your right, It's the animated button😆, we can remove and redirect the generate process to whoever is doing the Bulma CSS and HTML pages on the button their doing.

**Review by Amanda-Lacroix — APPROVED** [review]
looks good!

**Pull request merged**
